### ISSUE TITLE
Error when installing with FastAPI 0.71 &  Starlette 0.17.1

### ISSUE THREAD

**Issue by jnfinitym** [iwpnd/fastapi-key-auth#60]
**Descroption:** 
When using pip to install the current version of FastAPI-Key-Auth install fails with the following error message: 

```bash
ERROR: fastapi-key-auth 0.7.0 has requirement fastapi<0.71.0,>=0.70.0, but you'll have fastapi 0.71.0 which is incompatible.
ERROR: fastapi-key-auth 0.7.0 has requirement starlette<0.17.0,>=0.16.0, but you'll have starlette 0.17.1 which is incompatible.
```

**suggested Fix**
Update dependency to allow for newer version

**Comment by iwpnd** [comment]
Updated in 0.7.1, thanks for reaching out. 🙏
