### ISSUE TITLE
Cannot install with recent FastAPI

### ISSUE THREAD

**Issue by kehh** [iwpnd/fastapi-key-auth#97]
I'm currently getting an issue with installing with the lastest FastAPI. This looks to be very similar to #60 

I see that Dependabot has already updated the dependencies. Any chance you could roll a new release? TIA.
```
ERROR: Cannot install -r requirements.txt (line 4) and fastapi==0.75.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested fastapi==0.75.2
    fastapi-key-auth 0.7.1 depends on fastapi<0.72.0 and >=0.71.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by iwpnd** [comment]
Hi! 👋  You seem to be using an older version of fastapi-key-auth. The current one is compatible with fastapi up to 0.76.0.

**Comment by kehh** [comment]
Hi!
I've got the following in my requirements.txt:
```
fastapi==0.75.2
fastapi-key-auth==0.7.1
```
I've just put these into a separate requirements.txt in a clean virtualenv and I still get the same error:
```
ERROR: Cannot install -r requirements.txt (line 2) and fastapi==0.75.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested fastapi==0.75.2
    fastapi-key-auth 0.7.1 depends on fastapi<0.72.0 and >=0.71.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by iwpnd** [comment]
hm, I just got the package from pip and encounter the same issue. upon packaging the dependencies in the `setup.py` are changed to 

```
install_requires = \
['fastapi>=0.71.0,<0.72.0', 'starlette>=0.17.1,<0.18.0']
```

for whatever reason.

I just published a new release that should resolve your issue. Yet it leaves me dumbstruck as to why semantic versioning does that. 🤔

**Comment by iwpnd** [comment]
Ah, I think I brainfarted here and declared the dependency range the wrong way. `0.7.3` should now correctly support FastAPI `>=0.70.0,<0.76.0`

**Comment by kehh** [comment]
Thanks so much for jumping on this so quickly. 0.7.3 installs cleanly.
